apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp-server
  template:
    metadata:
      labels:
        app: sftp-server
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: sftp-server
        # --- השינוי הגדול: שימוש באימג' שלך ---
        # (החלף את הכתובת לכתובת האמיתית ב-GCP שלך)
        image: me-west1-docker.pkg.dev/sky-geo-dig-dev-u-dlab-1/production-system/sftp-server:v1

        # --- ניקוי: מחקנו את command ו-args ---
        # (האימג' כבר יודע להריץ את השרת לבד)

        resources:
           limits:
             memory: "256Mi"
             cpu: "500m"

        # הגדרת משתנים (אופציונלי - אם לא תגדיר, יילקחו ברירות המחדל מה-Dockerfile)
        env:
        - name: SFTP_USER
          value: "user1"     # או למשוך מ-Secret
        - name: SFTP_PASS
          value: "pass123"   # או למשוך מ-Secret
        - name: ALLOW_DELETE
          value: "true"
        - name: PYTHONUNBUFFERED
          value: "1"

        ports:
        - containerPort: 2222

        volumeMounts:
        - name: storage
          mountPath: /data
        # --- ניקוי: לא צריך יותר למפות את script-vol (/app) ---

      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: sftp-pvc-rwx
      # --- ניקוי: לא צריך יותר את ה-ConfigMap של הסקריפטים ---
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-service
spec:
  selector:
    app: sftp-server
  ports:
    - name: sftp
      port: 2222
      targetPort: 2222
  type: ClusterIP